name: bambootrace
description: A bamboo supply chain tracking Flutter application
publish_to: 'none' # since this is likely a private project

version: 1.0.0+1

environment:
  sdk: ">=3.8.0 <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # Network requests and secure token storage
  http: ^1.1.0
  flutter_secure_storage: ^9.2.2
  image_picker: ^1.1.2

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
